### PR TITLE
Bug fix for speech translation data preparation

### PR DESCRIPTION
**Pull request by jmp84**
Bug introduced in https://github.com/pytorch/fairseq/commit/d974c709bf57cf494738a824a1597e1886bebb7a I believe.

### CODE REVIEW

**Review by kahne — APPROVED** [review]
Thanks!

**Comment by voidmagic** [comment]
It may not be a bug.

I followed the instructions in [S2T Example: Speech Translation (ST) on MuST-C](https://github.com/pytorch/fairseq/blob/main/examples/speech_to_text/docs/mustc_example.md), and run this command:
```
python examples/speech_to_text/prep_mustc_data.py \
  --data-root ${MUSTC_ROOT} --task asr \
  --vocab-type unigram --vocab-size 5000
```

In the latest version, I got errors:
```
Fetching split train...
Extracting log mel filter bank features...
  0%|                                                                                                                              | 0/229703 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/qwang/.tools/fairseq/examples/speech_to_text/prep_mustc_data.py", line 294, in <module>
    main()
  File "/home/qwang/.tools/fairseq/examples/speech_to_text/prep_mustc_data.py", line 290, in main
    process(args)
  File "/home/qwang/.tools/fairseq/examples/speech_to_text/prep_mustc_data.py", line 141, in process
    features = extract_fbank_features(
  File "/home/qwang/.tools/fairseq/examples/speech_to_text/data_utils.py", line 90, in extract_fbank_features
    features = _get_torchaudio_fbank(_waveform, sample_rate, n_mel_bins)
  File "/home/qwang/.tools/fairseq/fairseq/data/audio/audio_utils.py", line 153, in _get_torchaudio_fbank
    features = ta_kaldi.fbank(
  File "/home/qwang/.miniconda/lib/python3.9/site-packages/torchaudio/compliance/kaldi.py", line 561, in fbank
    waveform, window_shift, window_size, padded_window_size = _get_waveform_and_window_properties(
  File "/home/qwang/.miniconda/lib/python3.9/site-packages/torchaudio/compliance/kaldi.py", line 139, in _get_waveform_and_window_properties
    waveform = waveform[channel, :]  # size (n)
IndexError: too many indices for tensor of dimension 1
```

By replacing `_waveform = _waveform[0].numpy()` with `_waveform = _waveform.numpy()` (simply reverting this commit), the error disappear!

### Environment:
Pytorch=1.10.1, py3.9_cuda11.3_cudnn8.2.0_0
fairseq: 1b61bbad327d2bf32502b3b9a770b57714cc43dc (install from source)
torchaudio: 0.10.1+cu113


**I did not install pykaldi,** and found the [following lines](https://github.com/pytorch/fairseq/blob/1b61bbad327d2bf32502b3b9a770b57714cc43dc/examples/speech_to_text/data_utils.py#L88):
```
    features = _get_kaldi_fbank(_waveform, sample_rate, n_mel_bins)
    if features is None:
        features = _get_torchaudio_fbank(_waveform, sample_rate, n_mel_bins)
```

In my settings, my code calls the function `_get_torchaudio_fbank` which fits with `_waveform = _waveform.numpy()`. 

This commit use  `_waveform = _waveform[0].numpy()`, and it may work with `_get_kaldi_fbank ` I guess.

Can anyone recheck this commit and test with the two cases torchaudio fbank and kaldi fbank please?

**Comment by jmp84** [comment]
@voidmagic the discussion in https://github.com/pytorch/fairseq/pull/3887 looks relevant. cc @kahne

**Comment by kahne** [comment]
@voidmagic Thanks very much for reporting! As discussed in the relevant PR that @jmp84 pointed out, this is a bug and we will include the fix in our next batch of bug fixes (coming next Monday).

**Pull request closed without merging**
