### PR TITLE
Fix bugs in MuST-C preprocessing

### LINKED ISSUE #3882: Bugs in S2T data_utils.py
## 🐛 Bug

There are two bugs in this file.

### Bug in [`extract_fbank_features`](https://github.com/pytorch/fairseq/blob/f6abcc2a67328bee8b15c596bb626ce2d720aae6/examples/speech_to_text/data_utils.py#L73-L98) function

The following line:
https://github.com/pytorch/fairseq/blob/f6abcc2a67328bee8b15c596bb626ce2d720aae6/examples/speech_to_text/data_utils.py#L83

Should be substituted by:
```python
_waveform, _ = convert_waveform(waveform, sample_rate, to_mono=True)
```

Because the function [`convert_waveform`](https://github.com/pytorch/fairseq/blob/f6abcc2a67328bee8b15c596bb626ce2d720aae6/fairseq/data/audio/audio_utils.py#L19) also returns the sample_rate:
https://github.com/pytorch/fairseq/blob/f6abcc2a67328bee8b15c596bb626ce2d720aae6/fairseq/data/audio/audio_utils.py#L61

### Bug in [`create_zip`](https://github.com/pytorch/fairseq/blob/f6abcc2a67328bee8b15c596bb626ce2d720aae6/examples/speech_to_text/data_utils.py#L101-L105) function

The following line:
https://github.com/pytorch/fairseq/blob/f6abcc2a67328bee8b15c596bb626ce2d720aae6/examples/speech_to_text/data_utils.py#L102

Does not work when executing [`prep_mustc_data.py`](https://github.com/pytorch/fairseq/blob/f6abcc2a67328bee8b15c596bb626ce2d720aae6/examples/speech_to_text/prep_mustc_data.py) with `--use-audio-input`, because the files extension is `.flac`.

It is necessary to add the following line below:
```python
paths.extend(data_root.glob("*.flac"))
```

### LINKED ISSUE #3884: Bugs in S2T prep_mustc_data.py
## 🐛 Bug

There are two bugs in [`prep_mustc_data.py`](https://github.com/pytorch/fairseq/blob/f6abcc2a67328bee8b15c596bb626ce2d720aae6/examples/speech_to_text/prep_mustc_data.py).

### Bug in the call of [`sf.write`](https://github.com/pytorch/fairseq/blob/f6abcc2a67328bee8b15c596bb626ce2d720aae6/examples/speech_to_text/prep_mustc_data.py#L130-L133)

https://github.com/pytorch/fairseq/blob/f6abcc2a67328bee8b15c596bb626ce2d720aae6/examples/speech_to_text/prep_mustc_data.py#L130-L133

While `_wavform` has the format `(channels x frames)`, the [`sf.write`](https://github.com/bastibe/python-soundfile/blob/744efb4b01abc72498a96b09115b42a4cabd85e4/soundfile.py#L263-L316) function expects the format `(frames x channels)`.

This caused a `RuntimeError: Error opening 'XXXXX': Format not recognised.`.

To solve it, it is needed to transpose `_wavform`: `_wavform.T.numpy()`

### Bug in the call of [`get_zip_manifest`](https://github.com/pytorch/fairseq/blob/f6abcc2a67328bee8b15c596bb626ce2d720aae6/examples/speech_to_text/prep_mustc_data.py#L159)

https://github.com/pytorch/fairseq/blob/f6abcc2a67328bee8b15c596bb626ce2d720aae6/examples/speech_to_text/prep_mustc_data.py#L159

This function has the argument `is_audio`, which is `False` by default.

It should be set accordingly depending on if using `--use-audio-input` or not:
```python
audio_paths, audio_lengths = get_zip_manifest(
    zip_path,
    is_audio=args.use_audio_input,
)
```

### PR DESCRIPTION
**Pull request by gegallego**
# Before submitting

- [X] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [X] Did you read the [contributor guideline](https://github.com/pytorch/fairseq/blob/master/CONTRIBUTING.md)?
- [ ] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  

## What does this PR do?
Fixes #3882
Fixes #3884 

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by gegallego** [comment]
Hi @kahne, #3882 was **partially** closed in #3921. However, I think the solution I propose here is cleaner, and it also considers some problems with `--use-audio-input`(#3882 & #3884).
Are you planning to merge it some day? Thank you.

**Comment by kahne** [comment]
> Hi @kahne, #3882 was **partially** closed in #3921. However, I think the solution I propose here is cleaner, and it also considers some problems with `--use-audio-input`(#3882 & #3884). Are you planning to merge it some day? Thank you.

Thanks! I've imported it for internal code review.

**Comment by holyma** [comment]
Hi, @kahne , this commit introduces a small bug [#98ebe4f
](https://github.com/pytorch/fairseq/commit/98ebe4f1ada75d006717d84f9d603519d8ff5579)

the following line:https://github.com/pytorch/fairseq/blob/87d0ede93c06f564b7b985c1a9a0489ae946313d/examples/speech_to_text/data_utils.py#L86
should be replaced：
```
 _waveform = _waveform.numpy()
```
because you have altered [line83](https://github.com/pytorch/fairseq/blob/87d0ede93c06f564b7b985c1a9a0489ae946313d/examples/speech_to_text/data_utils.py#L83) in that commit

**Comment by gegallego** [comment]
Yes, you're right. That line was changed by #3921, and it should have been reverted when introducing the changes of the current PR.

**Comment by kahne** [comment]
Thanks! I will revert the change.

**Pull request closed without merging**
