### PR TITLE
Fixing and error related to Floor Division

### PR DESCRIPTION
**Pull request by choprahetarth**
# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [x] Did you read the [contributor guideline](https://github.com/pytorch/fairseq/blob/main/CONTRIBUTING.md)?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

## What does this PR do?
Fixes #4058 
While using the library the following warnings are shown which sometimes hinder the workflow. The warnings are 

`<USER_PATH>/fairseq/search.py:140: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  beams_buf = indices_buf // vocab_size`

`<USER_PATH>/fairseq/sequence_generator.py:666: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  unfin_idx = bbsz_idx // beam_size`

The methodology was simple, instead of using the `//`, it was replaced by `torch.div(arg1, arg2, rounding_mode='trunc')` and the variable alues do not change for both before and after, just the warning is resolved. 

## PR review
Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃
Yes, I did! Thanks!

### CODE REVIEW

**Comment by choprahetarth** [comment]
@soumith 
Hi! I came across your profile while searching about Pytorch Maintainers. 
As you can see that this is my first PR in this repository and I was unable to request a reviewer which I can add usually. 
Sorry to ask you for this, but it would be really great if you could guide me what exactly should I do, since I do believe this PR can help PyTorch (I am working on an internal project, that uses fairseq, which is benefitting from this PR's change). 

Really looking forward to your reply
Thanks and Regards

**Comment by soumith** [comment]
I'd expect someone like @alexeib or @sravyapopuri388 can help?

**Comment by choprahetarth** [comment]
@alexeib Can you please help me with this pull request?

**Comment by sravyapopuri388** [comment]
It seems the changes are only compatible with pytorch version 1.8 or later. Many of us are still using pytorch 1.7, so is it possible to revert these changes? cc @alexeib

**Comment by choprahetarth** [comment]
@sravyapopuri388 if you want I can add an IF condition for the changes to take place only if the pytorch version is >=1.8.

**Comment by sravyapopuri388** [comment]
That would be helpful. Thanks @choprahetarth

**Pull request closed without merging**
