### PR TITLE
backout Reland [transformer] BT enablement on fairseq - fairseq change

### PR DESCRIPTION
**Pull request by frank-wei**
# Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [x] Did you read the [contributor guideline](https://github.com/pytorch/fairseq/blob/main/CONTRIBUTING.md)?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

## What does this PR do?
Revert the PR #4513 since that PR will break the torchscript of quantized model.

## PR review
Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by frank-wei** [comment]
@dianaml0  the test looks like flaky?

**Comment by dianaml0** [comment]
@frank-wei yes the breaking test is unrelated, fixing that separately. Could you just make sure that you use the pre-commit hook for this (run `flake8` and `black`) before submitting?

**Comment by dianaml0** [comment]
Could you also update the PR with a link to the PR you're reverting and a quick description?

**Comment by frank-wei** [comment]
> @frank-wei yes the breaking test is unrelated, fixing that separately. Could you just make sure that you use the pre-commit hook for this (run `flake8` and `black`) before submitting?

yes I did.

**Comment by frank-wei** [comment]
> Could you also update the PR with a link to the PR you're reverting and a quick description?

Updated.

**Review by dianaml0 — APPROVED** [review]

**Pull request merged**
