### PR TITLE
Add fix and back compat for changed private omegaconf api

### PR DESCRIPTION
**Pull request by voznesenskym**
Alternatively, we could pin a version of omegaconf

# Before submitting

- [X ] Was this discussed/approved via a Github issue? (no need for typos, doc improvements) No
- [X ] Did you read the [contributor guideline](https://github.com/pytorch/fairseq/blob/main/CONTRIBUTING.md)? Yes
- [X ] Did you make sure to update the docs? N/A
- [ X] Did you write any new necessary tests? N/A

## What does this PR do?
No issue opened, but noticed when running torchbenchmark

## Did you have fun?
The most fun you can have with your clothes on

### CODE REVIEW

**Comment by WilliamTambellini** [comment]
Thanks @voznesenskym 
Facing same blocking issue when running simple torch hub examples: 
```
  File "/home/wtambellini/.cache/torch/hub/pytorch_fairseq_main/fairseq/dataclass/utils.py", line 367, in __init__
    self.old_is_primitive = _utils.is_primitive_type
AttributeError: module 'omegaconf._utils' has no attribute 'is_primitive_type'
```
with
```
Requirement already satisfied: omegaconf in /usr/local/lib/python3.8/dist-packages (2.2.1)
```
No CI test to catch such regression ?

**Review by WilliamTambellini — APPROVED** [review]

**Comment by alexeib** [comment]
are you using omegaconf version from requirements.py?

**Comment by WilliamTambellini** [comment]
hum, which file ? 
```
~/repos/fairseq (main) $ find . -iname requirements*
./docs/requirements.txt
```

**Comment by alexeib** [comment]
ah sorry i mean setup.py
https://github.com/facebookresearch/fairseq/blob/main/setup.py

```
        install_requires=[
            "cffi",
            "cython",
            'dataclasses; python_version<"3.7"',
            "hydra-core>=1.0.7,<1.1",
            "omegaconf<2.1",
            'numpy<1.20.0; python_version<"3.7"',
            'numpy; python_version>="3.7"',
            "regex",
            "sacrebleu>=1.4.12",
            "torch",
            "tqdm",
            "bitarray",
            "torchaudio>=0.8.0",
        ],
        ```

**Comment by voznesenskym** [comment]
I believe I am on 2.0.6, as I ran the setup/install script specified in the README.md (`pip install --editable ./) and it passed.

I am working on torchdynamo, and I found this when running torchbenchmark. 

Fixing this moves me to the next error:

```
The strict flag in the compose API is deprecated.
...
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/data/home/voz/miniconda3/lib/python3.9/site-packages/omegaconf/basecontainer.py", line 626, in _wrap_value_and_set
    wrapped = _maybe_wrap(
  File "/data/home/voz/miniconda3/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 1070, in _maybe_wrap
    return _node_wrap(
  File "/data/home/voz/miniconda3/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 1027, in _node_wrap
    node = AnyNode(value=value, key=key, parent=parent)
  File "/data/home/voz/miniconda3/lib/python3.9/site-packages/omegaconf/nodes.py", line 135, in __init__
    super().__init__(
  File "/data/home/voz/miniconda3/lib/python3.9/site-packages/omegaconf/nodes.py", line 29, in __init__
    self._set_value(value)  # lgtm [py/init-calls-subclass]
  File "/data/home/voz/miniconda3/lib/python3.9/site-packages/omegaconf/nodes.py", line 46, in _set_value
    self._val = self.validate_and_convert(value)
  File "/data/home/voz/miniconda3/lib/python3.9/site-packages/omegaconf/nodes.py", line 76, in validate_and_convert
    return self._validate_and_convert_impl(value)
  File "/data/home/voz/miniconda3/lib/python3.9/site-packages/omegaconf/nodes.py", line 154, in _validate_and_convert_impl
    raise UnsupportedValueType(
omegaconf.errors.UnsupportedValueType: Value 'Namespace' is not a supported primitive type
    full_key: task
    object_type=dict
    ```

**Comment by alexeib** [comment]
its because the way you fixed it creates this error. that primitive type thing is monkey patching omegaconf to allow you to set a namespace object as a config value. you must have some wrong version of omegaconf if it has a different impl now for type checking

**Comment by voznesenskym** [comment]
> its because the way you fixed it creates this error. that primitive type thing is monkey patching omegaconf to allow you to set a namespace object as a config value. you must have some wrong version of omegaconf if it has a different impl now for type checking

Not 100% - the error is valid, but I bet the name of the thing we are monkeypatching changed. Fixing PR  to get past this, I missed the enter and exit calls. 

In general, I agree w/ @WilliamTambellini - if we're gonna do stuff like this (monkey patching, private APIs, etc), we need to have a CI script that ensures it all works and can install.

**Comment by WilliamTambellini** [comment]
Downgrading to omegaconf==2.2.0
seems to also resolve the issue but I still dont see any requirements.txt in the repo (except the one from the doc).

**Comment by voznesenskym** [comment]
@WilliamTambellini would you be able to try w/ this fix?

**Comment by alexeib** [comment]
it was always meant to be a temporary solution until the argparse config thing is phased out, which of course hasnt happened :P but maybe soon!

**Comment by voznesenskym** [comment]
Note: "First-time contributors need a maintainer to approve running workflows. [Learn more.](https://docs.github.com/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks)" 

If you guys have a moment, would you help me run the workflow?

**Comment by voznesenskym** [comment]
Thanks for the run @alexeib. CI for MacOS seems to fail with unrelated errors, while ubuntu passes. This feels like a flaky CI job, as the code should have nothing to do w/ OS.

Would you be able to kick off another run for me?

**Comment by WilliamTambellini** [comment]
Master as today seems to install 2.0.6:
```
python3.8 -m pip install --editable ./
...
Successfully installed antlr4-python3-runtime-4.8 fairseq hydra-core-1.0.7 omegaconf-2.0.6 torch-1.11.0 torchaudio-0.11.0
```

**Comment by voznesenskym** [comment]
Checks passed, diff stamped, would a reviewer mind merging in the PR?

**Pull request closed without merging**
