### PR TITLE
Mention Hugging Face integration

### PR DESCRIPTION
**Pull request by LysandreJik**
This PR completes the mention of the HuggingFace integration to the `nllb` integration.

Open for comments!

### CODE REVIEW

**Review by cbalioglu — APPROVED** [review]

**Comment by LysandreJik** [comment]
Hey @cbalioglu, how can I help to get this merged?

**Comment by cbalioglu** [comment]
> Hey @cbalioglu, how can I help to get this merged?

@LysandreJik just merged!

**Comment by LysandreJik** [comment]
Super cool, thank you!

**Comment by vedanuj** [comment]
This PR messed up the formatting of the Readme. Kindly fix it.

**Pull request merged**
