### PR TITLE
Update hubert config for compatibility to recent wav2vec2 update

### LINKED ISSUE #4035: Compatibility issue to Hubert from recent wav2vec2 updates
## 🐛 Bug

According to [recent updates](https://github.com/pytorch/fairseq/commit/7fd643552041f9aa81dd3085068176a97ef62e84) to wav2vec2 transformer encoder, the original hubert encoder initialization cannot work due to missing `checkpiont_activations`

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

```
from fairseq.models.hubert.hubert import (
    HubertModel,  # noqa: H301
    HubertConfig,  # noqa: H301
    HubertPretrainingConfig,  # noqa: H301
)
from fairseq.data.dictionary import Dictionary

cfg = HubertConfig()
hubert_task_cfg = HubertPretrainingConfig()

model = HubertModel(cfg, hubert_task_cfg, dictionaries)
```

The Error message would be:
```
    def __init__(self, args):
        super().__init__()
    
        self.dropout = args.dropout
        self.embedding_dim = args.encoder_embed_dim
    
        self.pos_conv = nn.Conv1d(
            self.embedding_dim,
            self.embedding_dim,
            kernel_size=args.conv_pos,
            padding=args.conv_pos // 2,
            groups=args.conv_pos_groups,
        )
        dropout = 0
        std = math.sqrt((4 * (1.0 - dropout)) / (args.conv_pos * self.embedding_dim))
        nn.init.normal_(self.pos_conv.weight, mean=0, std=std)
        nn.init.constant_(self.pos_conv.bias, 0)
    
        self.pos_conv = nn.utils.weight_norm(self.pos_conv, name="weight", dim=2)
        self.pos_conv = nn.Sequential(self.pos_conv, SamePad(args.conv_pos), nn.GELU())
    
        layers = []
        for _ in range(args.encoder_layers):
            layer = TransformerSentenceEncoderLayer(
                    embedding_dim=self.embedding_dim,
                    ffn_embedding_dim=args.encoder_ffn_embed_dim,
                    num_attention_heads=args.encoder_attention_heads,
                    dropout=self.dropout,
                    attention_dropout=args.attention_dropout,
                    activation_dropout=args.activation_dropout,
                    activation_fn=args.activation_fn,
                    layer_norm_first=args.layer_norm_first,
            )
>           if args.checkpoint_activations:
E           AttributeError: 'HubertConfig' object has no attribute 'checkpoint_activations'

tools/fairseq/fairseq/models/wav2vec/wav2vec2.py:856: AttributeError
```

### Environment

 - fairseq Version (e.g., 1.0 or main):
 - PyTorch Version 1.10
 - OS: linux
 - How you installed fairseq: pip
 - Python version: 3.9
 - CUDA/cuDNN version: 10.2

### Possible solution

An easy solution would be adding `checkpoint_activations` in the system. If your guys think it's OK. I can submit a PR towards that.

### PR DESCRIPTION
**Pull request by ftshijt**
This PR fixes #4035

### CODE REVIEW

**Review by arbabu123 — APPROVED** [review]
looks good. thanks!

**Comment by ftshijt** [comment]
Are there any other issues related to the PR? I'm happy to modify the PR if you have any other suggestions.

**Comment by arbabu123** [comment]
@ftshijt sorry I missed this. it looks good. i will merge this soon. thanks

**Comment by ftshijt** [comment]
Hi @arbabu123 , may I know why the PR is closed? In fact, we have the dependency of fairseq in our toolkit, and this mismatch breaks our CI tests for a while, so we can only depend on the older version. We really want to keep updated with the latest repo, it would be very helpful to fix the issue

**Comment by arbabu123** [comment]
@ftshijt sorry i didn't understand the issue. The fix has been landed and merged to master. What's the mismatch that you are talking about? What is the error that you are getting?

**Pull request closed without merging**
